name: multijob workflow
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up node
        uses: actions/setup-node@v4
        with: 
          node-version: '19.3.0'
      - name: restore dependencies
        run: npm ci
      - name: run lint
        run: npm run lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up node
        uses: actions/setup-node@v4
        with: 
          node-version: '19.3.0'
      - name: restore dependencies
        run: npm ci
      - name: build project
        run: npm run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up node
        uses: actions/setup-node@v4
        with: 
          node-version: '19.3.0'
      - name: restore dependencies
        run: npm ci
      - name: run tests
        run: npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "deploying project...."